# Generated by Django 4.0.5 on 2022-06-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('prizeSupport', models.IntegerField(default=0)),
                ('entry', models.IntegerField(default=0)),
                ('registrationLink', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('top8', models.BooleanField(default=False)),
                ('cap', models.IntegerField(default=0)),
            ],
        ),
    ]
