# Generated by Django 4.0.5 on 2022-06-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
