# Generated by Django 4.0.5 on 2022-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0004_punch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punch',
            old_name='time',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='punch',
            name='time_out',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
